### PR TITLE
Add a docstring for VecUnroll

### LINKED ISSUE #71: Docstring for VecUnroll?
I'm looking into providing support for multichannel colors in ImageFiltering. As you may know, JuliaImages provides real RGB types that encode the color of a pixel without adding an array dimension to do it. Naturally, these aren't natively supported by VectorizationBase. Obviously, I can `reinterpret(reshape, Float32 #=or whatever=#, img)`, but everything gets a lot uglier if you have to add array dimensions. I am guessing that `VecUnroll` is kind of like a `SVector`, is that right? If so, what do the parameters "mean"? Or if that's not the case, is there a good solution for supporting the equivalent of an `NTuple{N,T} where T<:NativeTypes`?

### PR DESCRIPTION
**Pull request by timholy**
Closes #71

### CODE REVIEW

**Comment by timholy** [comment]
Please feel free to edit at will!

**Comment by chriselrod** [comment]
The other advantage is that it allows interleaving instructions, which can take better advantage of a CPU's OOO:
```julia
julia> using VectorizationBase, SLEEFPirates

julia> vx = Vec(ntuple(_ -> randn(), pick_vector_width(Float64))...)
Vec{8, Float64}<-0.41777997881994483, -0.2778225158869686, 1.0569948436617753, 0.5176464757147176, 0.2323833794303069, -0.7993648787803678, -0.9685718051710357, 0.12727761225970358>

julia> vxu = VecUnroll((vx,vx,vx,vx));

julia> @btime exp2($(Ref(vx))[])
  4.348 ns (0 allocations: 0 bytes)
Vec{8, Float64}<0.7485756477631421, 0.8248350157271293, 2.0805930967801856, 1.431617888324136, 1.174774112297017, 0.5746020803268009, 0.5110116881622035, 1.0922306992794324>

julia> @btime exp2($(Ref(vxu))[])
  9.461 ns (0 allocations: 0 bytes)
4 x Vec{8, Float64}
Vec{8, Float64}<0.7485756477631421, 0.8248350157271293, 2.0805930967801856, 1.431617888324136, 1.174774112297017, 0.5746020803268009, 0.5110116881622035, 1.0922306992794324>
Vec{8, Float64}<0.7485756477631421, 0.8248350157271293, 2.0805930967801856, 1.431617888324136, 1.174774112297017, 0.5746020803268009, 0.5110116881622035, 1.0922306992794324>
Vec{8, Float64}<0.7485756477631421, 0.8248350157271293, 2.0805930967801856, 1.431617888324136, 1.174774112297017, 0.5746020803268009, 0.5110116881622035, 1.0922306992794324>
Vec{8, Float64}<0.7485756477631421, 0.8248350157271293, 2.0805930967801856, 1.431617888324136, 1.174774112297017, 0.5746020803268009, 0.5110116881622035, 1.0922306992794324>

julia> @btime sin($(Ref(vx))[])
  8.536 ns (0 allocations: 0 bytes)
Vec{8, Float64}<-0.40573237311580634, -0.2742623121079716, 0.8708824084181056, 0.49483633008673605, 0.2302974902834125, -0.7169134530311316, -0.8240775144694545, 0.1269342496262836>

julia> @btime sin($(Ref(vxu))[])
  21.154 ns (0 allocations: 0 bytes)
4 x Vec{8, Float64}
Vec{8, Float64}<-0.40573237311580634, -0.2742623121079716, 0.8708824084181056, 0.49483633008673605, 0.2302974902834125, -0.7169134530311316, -0.8240775144694545, 0.1269342496262836>
Vec{8, Float64}<-0.40573237311580634, -0.2742623121079716, 0.8708824084181056, 0.49483633008673605, 0.2302974902834125, -0.7169134530311316, -0.8240775144694545, 0.1269342496262836>
Vec{8, Float64}<-0.40573237311580634, -0.2742623121079716, 0.8708824084181056, 0.49483633008673605, 0.2302974902834125, -0.7169134530311316, -0.8240775144694545, 0.1269342496262836>
Vec{8, Float64}<-0.40573237311580634, -0.2742623121079716, 0.8708824084181056, 0.49483633008673605, 0.2302974902834125, -0.7169134530311316, -0.8240775144694545, 0.1269342496262836>
```
In these example, 4x the work takes less than 2.5x the time.

**Comment by timholy** [comment]
Do you want me to change the docstring in some way? I do use the word `interleave` but don't talk about the performance optimizations (which, as always, are cool). I could basically paste your demo, but I worry about making it quite long. This version emphasizes *defining* it without going into extensive detail about *using* it. The balance may not be quite right, though.

**Comment by chriselrod** [comment]
The test that failed is `bwap` on random floating point values, which is likely to (correctly) produce `NaN`s, so I've updated the test on master to use `isequal` instead of `==`.
So I went ahead and merged, thanks!

> Do you want me to change the docstring in some way? I do use the word `interleave` but don't talk about the performance optimizations (which, as always, are cool). I could basically paste your demo, but I worry about making it quite long.

I agree, that'd be long.
It already mentions some optimizations, so users may assume that it can help in other contexts.

> This version emphasizes defining it without going into extensive detail about using it. The balance may not be quite right, though.

It should be usable wherever other `AbstractSIMD`s are, so ideally not much explanation is needed and focusing on construction is the way to go.

**Pull request merged**
